"""Initial migration

Revision ID: 263a0849a227
Revises: 
Create Date: 2026-03-19 09:01:53.120730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263a0849a227'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('SOLE_PROPRIETORSHIP', 'SINGLE_MEMBER_LLC', 'PARTNERSHIP', 'S_CORP', 'C_CORP', 'LLC_PARTNERSHIP', 'LLC_S_CORP', 'LLC_C_CORP', name='entitytype'), nullable=False),
    sa.Column('ein', sa.String(length=10), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_code', sa.String(length=6), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('filing_status', sa.Enum('SINGLE', 'MARRIED_FILING_JOINTLY', 'MARRIED_FILING_SEPARATELY', 'HEAD_OF_HOUSEHOLD', 'QUALIFYING_WIDOWER', name='filingstatus'), nullable=True),
    sa.Column('accounting_method', sa.Enum('CASH', 'ACCRUAL', 'OTHER', name='accountingmethod'), nullable=False),
    sa.Column('has_inventory', sa.Boolean(), nullable=False),
    sa.Column('inventory_beginning', sa.Integer(), nullable=True),
    sa.Column('inventory_ending', sa.Integer(), nullable=True),
    sa.Column('ai_classification_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_user_id'), 'entities', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('item_id', sa.String(length=50), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('accounts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_bank_connections_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_connections'))
    )
    op.create_index(op.f('ix_bank_connections_entity_id'), 'bank_connections', ['entity_id'], unique=False)
    op.create_table('generated_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.Enum('SCHEDULE_C', 'FORM_1120', 'FORM_1120_S', 'FORM_1065', name='formtype'), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'REVIEWED', 'APPROVED', 'FILED', name='formstatus'), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('pdf_file', sa.String(length=255), nullable=True),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_generated_forms_entity_id_entities')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_generated_forms_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_forms'))
    )
    op.create_index(op.f('ix_generated_forms_entity_id'), 'generated_forms', ['entity_id'], unique=False)
    op.create_table('tax_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('gross_income', sa.Float(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('net_income', sa.Float(), nullable=False),
    sa.Column('taxable_income', sa.Float(), nullable=False),
    sa.Column('estimated_tax', sa.Float(), nullable=False),
    sa.Column('self_employment_tax', sa.Float(), nullable=False),
    sa.Column('effective_rate', sa.Float(), nullable=False),
    sa.Column('marginal_rate', sa.Float(), nullable=False),
    sa.Column('calculation_data', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_tax_calculations_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_calculations'))
    )
    op.create_index(op.f('ix_tax_calculations_entity_id'), 'tax_calculations', ['entity_id'], unique=False)
    op.create_table('transaction_imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('CSV', 'XLSX', 'PDF', 'PLAID', 'QUICKBOOKS', 'XERO', 'STRIPE', 'MANUAL', 'API', name='transactionsource'), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='importstatus'), nullable=False),
    sa.Column('transactions_imported', sa.Integer(), nullable=False),
    sa.Column('import_options', sa.JSON(), nullable=True),
    sa.Column('import_summary', sa.JSON(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_transaction_imports_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_imports'))
    )
    op.create_index(op.f('ix_transaction_imports_entity_id'), 'transaction_imports', ['entity_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sa.Enum('INCOME', 'EXPENSE', name='transactiondirection'), nullable=False),
    sa.Column('raw_description', sa.String(length=500), nullable=True),
    sa.Column('normalized_description', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('CSV', 'XLSX', 'PDF', 'PLAID', 'QUICKBOOKS', 'XERO', 'STRIPE', 'MANUAL', 'API', name='transactionsource'), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('classification_status', sa.Enum('PENDING', 'CLASSIFIED', 'REVIEW_REQUIRED', 'CONFIRMED', 'PRE_CLASSIFIED', name='classificationstatus'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tax_category', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('user_corrected', sa.Boolean(), nullable=False),
    sa.Column('plaid_category', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_transactions_entity_id_entities')),
    sa.ForeignKeyConstraint(['import_id'], ['transaction_imports.id'], name=op.f('fk_transactions_import_id_transaction_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_entity_id'), 'transactions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_transactions_tax_category'), 'transactions', ['tax_category'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_table('classification_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('original_category', sa.String(length=50), nullable=True),
    sa.Column('original_tax_category', sa.String(length=50), nullable=True),
    sa.Column('corrected_category', sa.String(length=50), nullable=False),
    sa.Column('corrected_tax_category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_classification_feedback_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classification_feedback'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classification_feedback')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tax_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_entity_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_transaction_imports_entity_id'), table_name='transaction_imports')
    op.drop_table('transaction_imports')
    op.drop_index(op.f('ix_tax_calculations_entity_id'), table_name='tax_calculations')
    op.drop_table('tax_calculations')
    op.drop_index(op.f('ix_generated_forms_entity_id'), table_name='generated_forms')
    op.drop_table('generated_forms')
    op.drop_index(op.f('ix_bank_connections_entity_id'), table_name='bank_connections')
    op.drop_table('bank_connections')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_entities_user_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
